server:
  port: 5076
  shutdown: graceful

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

  application:
    name: diyet-app-backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://3.71.43.116:30432/diyet-app}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: 1
      password: ${REDIS_PASSWORD:}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:3.71.43.116:30699}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: diyet-app-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.fatihdemir.diyetappbackend.kafka.event"
        spring.json.value.default.type: "com.fatihdemir.diyetappbackend.kafka.event.AppointmentEvent"

jwt:
  private-key-path: certs/private.pem
  public-key-path: certs/public.pem
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

firebase:
  web-api-key: ${FIREBASE_WEB_API_KEY}

security:
  rate-limit:
    max-attempts: 5
    block-duration-minutes: 30
    window-minutes: 15

kafka:
  topics:
    appointment-events: appointments-event
    appointment-events-dlt: appointments-event-dlt

resend:
  api-key: ${RESEND_API_KEY}